version: '3.8'
services:
  ch_server:
    container_name: ch_server
    build:
      context: .
      dockerfile: Dockerfile
    ports: 
      - '127.0.0.1:8123:8123'
      - '127.0.0.1:9000:9000'
    env_file:
      - .env
    volumes:
      - ch_data:/var/lib/clickhouse
      - ./sql-scripts:/docker-entrypoint-initdb.d
      - ./main.py:/app/main.py
      - ./.env:/app/.env
    command: >
      bash -c "
        /entrypoint.sh &&
        sleep 5 &&
        clickhouse-client --user=${CLICKHOUSE_USER:-click} --password=${CLICKHOUSE_PASSWORD:-click} --queries-file /docker-entrypoint-initdb.d/init_script.sql
      "

volumes:
  ch_data:
